interface MarketAnalysisData {
  keyInd: {
    location: {
      title: {
        value: number;
        percentage: number;
      };
    };
  };
  sellRentOverTime: {
    id: {
      Date: string;
      codLocation: string;
      'Pre\u00e7o m\u00e9dio_sell': number;
      'Pre\u00e7o m\u00e9dio_rent': number;
      localizacao: string;
    };
  };
  marketPhaseTrendsYearly: {
    id: {
      Year: number;
      'Pre\u00e7o m\u00e9dio_sell': number;
      'Propriedades vendida e retiradas_sell': number;
      'Price Change (%)': number;
      'Transaction Change (%)': number;
    };
  };
  marketDynamics: Array<{
    Date: string;
    localizacao: string;
    'Subida de pre\u00e7o_sell': number;
    'Redu\u00e7\u00e3o de pre\u00e7o_sell': number;
    'Novas propriedades \u00fanicas_sell': number;
    'Propriedades vendida e retiradas_sell': number;
    'Subida de pre\u00e7o_rent': number;
    'Redu\u00e7\u00e3o de pre\u00e7o_rent': number;
    'Novas propriedades \u00fanicas_rent': number;
    'Propriedades vendida e retiradas_rent': number;
    'Popula\u00e7\u00e3o desempregada com idade entre 16 e 74 anos (N.\u00ba) por Grupo et\u00e1rio; Mensal (2) ': number;
    'N\u00famero de benefici\u00e1rios de subs\u00eddio de desemprego (milhares)-mensal': number;
    'Desemprego registado no final do per\u00edodo-Total-Mensal': number;
    'Desemprego registado ao longo do per\u00edodo-Total-Mensal': number;
    '1 m\u00eas (Euribor)': number;
    '3 meses (Euribor)': number;
    '6 meses (Euribor)': number;
    '12 meses (Euribor)': number;
    'Endividamento dos particulares-TVA': number;
    'Endividamento dos particulares': number;
    'Endividamento dos particulares junto de empresas n\u00e3o financeiras': number;
  }>;
  propertyMarketData: Array<{
    title: string;
    mainImage: string;
    bedrooms_value: number;
    bathrooms_value: number;
    area_value: string;
    price: number;
    sale_price_per_sqm_value: string;
    days_on_market_value: string;
    new_rental_yield_value: string;
    localizacao: string;
    energy_rating_estate_page_value: string;
    last_price_change_value: string;
    combined_features: string[];
    label: string;
    sale_status_value: string;
    id: number;
    new_rental_yield_average_rent_price_value: string;
    construction_year_value: string;
    path: string;
    codlocation: string;
    Avaliacoes_Total: number;
    Avaliacoes_Apartamentos: number;
    Avaliacoes_Moradias: number;
    Capital_Divida_Total: number;
    Capital_Divida_3M: number;
    Capital_Divida_6M: number;
    Capital_Divida_12M: number;
    Juros_Totais: number;
    Capital_Amortizado: number;
    Populacao_Desempregada_Com_Idade_Entre_16_E_74_Anos_Por_Grupo_Etario_Mensal_2: number;
    Prestacao_Media: number;
    Meses: number;
    Ano: number;
    mes: number;
    ano: number;
    Euribor_1_Mes: number;
    Euribor_3_Meses: number;
    Euribor_6_Meses: number;
    Euribor_12_Meses: number;
    Numero_De_Beneficiarios_De_Subsidio_De_Desemprego_Milhares_Mensal: number;
    Indicador_Coincidente_Para_A_Atividade_Economica_Mensal_TVH: number;
    Indicador_Coincidente_Para_O_Consumo_Privado_Mensal_TVH: number;
    Endividamento_Dos_Particulares_TVA: number;
    Endividamento_Dos_Particulares: number;
    Endividamento_Dos_Particulares_Junto_De_Empresas_Nao_Financeiras: number;
    Endividamento_Dos_Particulares_Junto_Do_Setor_Financeiro: number;
    Endividamento_Dos_Particulares_Junto_Das_Administracoes_Publicas: number;
    Endividamento_Dos_Particulares_Junto_De_Particulares: number;
    Endividamento_Dos_Particulares_Junto_Do_Resto_Do_Mundo: number;
    Desemprego_Registrado_No_Final_Do_Periodo_Total_Mensal: number;
    Desemprego_Registrado_Ao_Longo_Do_Periodo_Total_Mensal: number;
    IPC_Total_Taxa_De_Variacao_Homogenea: number;
    IPC_Total_Taxa_De_Variacao_Em_Cadeia: number;
    IPC_Total_Taxa_De_Inflacao_Media_Anual_TVMM12: number;
    Taxa_De_Juro_TAA_Do_Stock_De_Emprestimos_As_Empresas_Nao_Financeiras: number;
    TAEG_De_Novos_Emprestimos_Ao_Consumo: number;
    TAEG_De_Novos_Emprestimos_A_Habitacao: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_Para_Outros_Fins: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_Ao_Consumo: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_A_Habitacao: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_Aos_Particulares: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_Acima_De_1M_As_Empresas_Nao_Financeiras: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_Ate_1M_As_Empresas_Nao_Financeiras: number;
    Taxa_De_Juro_TAA_De_Novos_Emprestimos_As_Empresas_Nao_Financeiras: number;
    dia: number;
    codLocation: string;
    Data: string;
    Preco_Medio_Sell: number;
    Preco_Medio_Por_M2_Sell: number;
    Preco_Medio_De_Fechamento_BETA_Sell: number;
    Preco_Medio_De_Fechamento_Por_M2_BETA_Sell: number;
    Subida_De_Preco_Sell: number;
    Reducao_De_Preco_Sell: number;
    Novas_Propriedades_Unicas_Sell: number;
    Propriedades_Vendida_E_Retiradas_Sell: number;
    Novas_Listagens_Nao_Desduplicadas_Sell: number;
    Preco_Medio_Rent: number;
    Preco_Medio_Por_M2_Rent: number;
    Preco_Medio_De_Fechamento_BETA_Rent: number;
    Preco_Medio_De_Fechamento_Por_M2_BETA_Rent: number;
    Subida_De_Preco_Rent: number;
    Reducao_De_Preco_Rent: number;
    Novas_Propriedades_Unicas_Rent: number;
    Propriedades_Vendida_E_Retiradas_Rent: number;
    Novas_Listagens_Nao_Desduplicadas_Rent: number;
    Dayi: number;
    Monthi: number;
    Yeari: number;
    Date: string;
    moving_avg_price_sell: number;
    exp_moving_avg_price_sell: number;
    price_to_rent_ratio: number;
    propriedades_unicas_rent: number;
    propriedades_unicas_sell: number;
    moving_avg_price_rent: number;
    exp_moving_avg_price_rent: number;
    moving_avg_Reducao_sell: number;
    moving_avg_Reducao_rent: number;
  }>;
}

export default MarketAnalysisData;
